[package]
name = "dubins_paths"
version = "0.1.0"
authors = ["VirxEC"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
