[package]
name = "dubins_paths"
version = "1.0.2"
authors = ["VirxEC"]
edition = "2021"
description = "Rust code for calculating Dubin's Paths"
readme = "README.md"
repository = "https://github.com/VirxEC/dubins_paths"
license = "GPL-3.0-only"
keywords = ["rocket-league", "rlbot", "physics", "simulation", "dubin"]
categories = ["science", "simulation", "algorithms"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
