[package]
name = "dubins_paths"
version = "1.7.1"
authors = ["VirxEC"]
edition = "2021"
description = "Rust code for calculating Dubin's Paths"
readme = "README.md"
repository = "https://github.com/VirxEC/dubins_paths"
license = "MIT"
keywords = ["rocket-league", "rlbot", "physics", "simulation", "dubin"]
categories = ["science", "simulation", "algorithms"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
rand = "0.8.5"

[dependencies]
glam = { version = "0.24.0", optional = true }

[features]
glam = ["dep:glam"]
fast-math = ["glam", "glam/fast-math"]

[profile.release]
codegen-units = 1
lto = true
panic = "abort"

[profile.release-with-debug]
inherits = "release"
debug = true
